mocap4r2_optitrack_driver_node:
  ros__parameters:
    connection_type: "Unicast"
    server_address: "192.168.1.130"
    local_address: "192.168.1.194"
    multicast_address: "239.255.42.99"
    server_command_port: 1510
    server_data_port: 1511
    rigid_body_name: "ground"
    rigid_body_ids: ["1", "2", "3", "4"]
    lastFrameNumber: 0
    frameCount: 0
    droppedFrameCount: 0
    n_markers: 0
    n_unlabeled_markers: 0
    qos_history_policy: "keep_all"
    qos_reliability_policy: "best_effort"
    qos_depth: 10